version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "month"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "month"
